version: '3.8'
services:
    catalogo-defectos:
      build: ./CatalogoDefectos
      expose:
        - "9003"
        - "8003"
      environment:
        - DB_HOST=db-catalogo-defectos
      depends_on:
        db-catalogo-defectos:
          condition: service_healthy
      networks:
        - red-global-despliegue
      
    catalogo-productos:
      build: ./CatalogoProductos
      expose:
        - "9001"
        - "8001"
      environment:
        - DB_HOST=db-catalogo-productos
      depends_on:
        db-catalogo-productos:
          condition: service_healthy
      networks:
        - red-global-despliegue

    servicio-inspecciones:
      build: ./ServicioInspecciones
      expose:
        - "8082"
        - "9010"
      environment:
        - DB_HOST=db-reportes-inspecciones
        - CATALOGO_PRODUCTOS_HOST=catalogo-productos
        - CATALOGO_DEFECTOS_HOST=catalogo-defectos
        - RABBITMQ_HOST=rabbitmq
      depends_on:
        db-reportes-inspecciones:
          condition: service_healthy
        catalogo-defectos:
          condition: service_started
        catalogo-productos:
          condition: service_started
      networks:
        - red-global-despliegue

    db-catalogo-defectos:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: CatalogoDefectos
        MYSQL_ROOT_PASSWORD: Itson
      expose:
        - "3306"
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pItson"]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 30s
      networks:
        - red-global-despliegue

    db-catalogo-productos:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: CatalogoProductos
        MYSQL_ROOT_PASSWORD: Itson
      expose:
        - "3306"
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pItson"]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 30s
      networks:
        - red-global-despliegue

    db-reportes-inspecciones:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: ReportesInspecciones
        MYSQL_ROOT_PASSWORD: Itson
      expose:
        - "3306"
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pItson"]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 30s
      networks:
        - red-global-despliegue

networks:
  red-global-despliegue:
    external: true
