version: '3.8'

services:
  sistema-qa:
    build: ./ServicioQA
    environment:
      - WS_SERVER_URL=servicio-notificaciones:8000
      - PYTHONUNBUFFERED=1
    networks:
      - red-global-despliegue

  sistema-erp:
    build: ./SistemaERP
    environment:
      - WS_SERVER_URL=servicio-notificaciones:8000
      - PYTHONUNBUFFERED=1
    networks:
      - red-global-despliegue

networks:
  red-global-despliegue:
    name: red-global-despliegue
    external: true