# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cambio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cambio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x61mbio.proto\x12\x08producto\"2\n\x11\x43onversionRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x01\"N\n\x12\x43onversionResponse\x12\x11\n\ttotal_mxn\x18\x01 \x01(\x01\x12\x11\n\ttotal_usd\x18\x02 \x01(\x01\x12\x12\n\ntasa_usada\x18\x03 \x01(\x01\"\x1e\n\x0fProductoRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\"\x81\x01\n\x10ProductoResponse\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x16\n\x0e\x63osto_unitario\x18\x03 \x01(\x01\x12$\n\x04tipo\x18\x04 \x01(\x0e\x32\x16.producto.TipoProducto\x12\x12\n\ndisponible\x18\x05 \x01(\x08\"Z\n\x0f\x43\x61talogoRequest\x12-\n\rtipo_producto\x18\x01 \x01(\x0e\x32\x16.producto.TipoProducto\x12\x18\n\x10solo_disponibles\x18\x02 \x01(\x08*\x82\x01\n\x0cTipoProducto\x12\x18\n\x14TIPO_NO_ESPECIFICADO\x10\x00\x12\x0b\n\x07LIQUIDO\x10\x01\x12\n\n\x06SOLIDO\x10\x02\x12\x0f\n\x0b\x43REMA_PASTA\x10\x03\x12\x07\n\x03GEL\x10\x04\x12\x0b\n\x07\x41\x45ROSOL\x10\x05\x12\t\n\x05POLVO\x10\x06\x12\r\n\tTOALLITAS\x10\x07\x32[\n\rCambioService\x12J\n\rGetConversion\x12\x1b.producto.ConversionRequest\x1a\x1c.producto.ConversionResponse2\xb5\x01\n\x0f\x43\x61talogoService\x12T\n\x19VerificarYObtenerProducto\x12\x19.producto.ProductoRequest\x1a\x1a.producto.ProductoResponse\"\x00\x12L\n\x0fObtenerCatalogo\x12\x19.producto.CatalogoRequest\x1a\x1a.producto.ProductoResponse\"\x00\x30\x01\x42\x1f\n\x1borg.itson.catalogoproductosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cambio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033org.itson.catalogoproductosP\001'
  _globals['_TIPOPRODUCTO']._serialized_start=415
  _globals['_TIPOPRODUCTO']._serialized_end=545
  _globals['_CONVERSIONREQUEST']._serialized_start=26
  _globals['_CONVERSIONREQUEST']._serialized_end=76
  _globals['_CONVERSIONRESPONSE']._serialized_start=78
  _globals['_CONVERSIONRESPONSE']._serialized_end=156
  _globals['_PRODUCTOREQUEST']._serialized_start=158
  _globals['_PRODUCTOREQUEST']._serialized_end=188
  _globals['_PRODUCTORESPONSE']._serialized_start=191
  _globals['_PRODUCTORESPONSE']._serialized_end=320
  _globals['_CATALOGOREQUEST']._serialized_start=322
  _globals['_CATALOGOREQUEST']._serialized_end=412
  _globals['_CAMBIOSERVICE']._serialized_start=547
  _globals['_CAMBIOSERVICE']._serialized_end=638
  _globals['_CATALOGOSERVICE']._serialized_start=641
  _globals['_CATALOGOSERVICE']._serialized_end=822
# @@protoc_insertion_point(module_scope)
