# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cambio_pb2 as cambio__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cambio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CambioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConversion = channel.unary_unary(
                '/producto.CambioService/GetConversion',
                request_serializer=cambio__pb2.ConversionRequest.SerializeToString,
                response_deserializer=cambio__pb2.ConversionResponse.FromString,
                _registered_method=True)


class CambioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetConversion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CambioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConversion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversion,
                    request_deserializer=cambio__pb2.ConversionRequest.FromString,
                    response_serializer=cambio__pb2.ConversionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'producto.CambioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('producto.CambioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CambioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConversion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/producto.CambioService/GetConversion',
            cambio__pb2.ConversionRequest.SerializeToString,
            cambio__pb2.ConversionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CatalogoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerificarYObtenerProducto = channel.unary_unary(
                '/producto.CatalogoService/VerificarYObtenerProducto',
                request_serializer=cambio__pb2.ProductoRequest.SerializeToString,
                response_deserializer=cambio__pb2.ProductoResponse.FromString,
                _registered_method=True)
        self.ObtenerCatalogo = channel.unary_stream(
                '/producto.CatalogoService/ObtenerCatalogo',
                request_serializer=cambio__pb2.CatalogoRequest.SerializeToString,
                response_deserializer=cambio__pb2.ProductoResponse.FromString,
                _registered_method=True)


class CatalogoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VerificarYObtenerProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCatalogo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerificarYObtenerProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarYObtenerProducto,
                    request_deserializer=cambio__pb2.ProductoRequest.FromString,
                    response_serializer=cambio__pb2.ProductoResponse.SerializeToString,
            ),
            'ObtenerCatalogo': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerCatalogo,
                    request_deserializer=cambio__pb2.CatalogoRequest.FromString,
                    response_serializer=cambio__pb2.ProductoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'producto.CatalogoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('producto.CatalogoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerificarYObtenerProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/producto.CatalogoService/VerificarYObtenerProducto',
            cambio__pb2.ProductoRequest.SerializeToString,
            cambio__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerCatalogo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/producto.CatalogoService/ObtenerCatalogo',
            cambio__pb2.CatalogoRequest.SerializeToString,
            cambio__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
