quarkus.datasource.db-kind=mysql

quarkus.datasource.jdbc.url=jdbc:mysql://${DB_HOST:localhost}:3306/ReportesInspecciones
quarkus.datasource.username=${DB_USER:root}
quarkus.datasource.password=${DB_PASS:itson}

quarkus.http.port=8082
quarkus.grpc.server.port=9010

quarkus.hibernate-orm.database.generation=update

# gRPC apuntando a las variables de entorno
quarkus.grpc.clients.catalogo-productos.host=${CATALOGO_PRODUCTOS_HOST:localhost}
quarkus.grpc.clients.catalogo-productos.port=9001
quarkus.grpc.clients.catalogo-defectos.host=${CATALOGO_DEFECTOS_HOST:localhost}
quarkus.grpc.clients.catalogo-defectos.port=9003


quarkus.grpc.clients.catalogo-productos.plain-text=true
quarkus.grpc.clients.catalogo-defectos.plain-text=true

# Configuraci\u00f3n para el broker apuntando a variables
rabbitmq.host=${RABBITMQ_HOST:localhost}
rabbitmq.port=5672
rabbitmq.username=${RABBITMQ_USER:admin}
rabbitmq.password=${RABBITMQ_PASS:admin}