quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/reportesInspecciones
quarkus.datasource.username=root
quarkus.datasource.password=Itson

quarkus.http.port=8082
quarkus.grpc.server.port=9010

quarkus.hibernate-orm.database.generation=update

quarkus.grpc.clients.catalogo-productos.host=localhost
quarkus.grpc.clients.catalogo-productos.port=9001
quarkus.grpc.clients.catalogo-defectos.host=localhost
quarkus.grpc.clients.catalogo-defectos.port=9003

# Aseguramos que los clientes NO usen SSL/TLS
quarkus.grpc.clients.catalogo-productos.plain-text=true
quarkus.grpc.clients.catalogo-defectos.plain-text=true