# Configuraci\u00f3n de la base de datos
quarkus.datasource.db-kind=mysql

quarkus.datasource.jdbc.url=jdbc:mysql://${DB_HOST:localhost}:3306/CatalogoDefectos
quarkus.datasource.username=${DB_USER:root}
quarkus.datasource.password=${DB_PASS:itson}

quarkus.http.port=8083
quarkus.grpc.server.port=9003

quarkus.hibernate-orm.database.generation=update