##  configuracion rabbitMQ  

# Habilitar el plugin de manejo con definiciones precargadas
management.load_definitions = /etc/rabbitmq/definitions.json

# Limites de memoria y disco
vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 1GB

# heartbeat para conexiones AMQP
heartbeat = 60

# Log level
log.console = true
log.console.level = info
